### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [nigelhorne/Locale-Places#1]
The test suite fails if some modules are not installed:
* DBD::SQLite::Constants
* Error::Simple

Additionally modules are needed in the Makefile.PL phase and thus need to be specified as configure_requires:
* LWP::Simple

**Comment by nigelhorne** [comment]
That should already have been fixed by https://github.com/nigelhorne/Locale-Places/commit/4c7d7f197590e3fa030ce902865143f02e495716

Please check the latest version.

**Comment by nigelhorne** [comment]
I believe that this was fixed in version 0.04.  If the problem persists, please re-open this ticket.
