### ISSUE TITLE
GitHub Actions: need to update freebsd version

### ISSUE THREAD

**Issue by eserte** [nigelhorne/Locale-Places#10]
Regarding https://github.com/nigelhorne/Locale-Places/actions/runs/10028766304/job/27716099749 : I think that freebsd 13.0 does not work anymore with cross-platform-actions/action. Probably it has to be updated to 13.3. I don't know about the openbsd versioning, but this could possibly be the same problem.

**Comment by nigelhorne** [comment]
Please report this to https://github.com/FGasper/perl-github-action-tips/issues/7

**Comment by nigelhorne** [comment]
Runner moved from macOS to ubuntu.
