### ISSUE TITLE
Endless loop with warnings in test suite

### ISSUE THREAD

**Issue by eserte** [nigelhorne/Locale-Places#6]
Currently all my smokers fill up when building Locale-Places-0.09. The logs repeat the following line:
```
Use of uninitialized value $headers[9] in hash slice at /opt/perl-5.30.3/lib/site_perl/5.30.3/Text/xSV/Slurp.pm line 651, <$handle> line 10342.
```

**Comment by nigelhorne** [comment]
Can you please set NO_NETWORK_TESTING and try again?  If that helps I will enable that when AUTOMATED_TESTING is set.

Also, it looks like GZip::Faster has no code to check for failure, e.g. if the disc fills, so I'll need to work around that.

**Comment by eserte** [comment]
This seems to stop the build:
```
...
NA: NO_NETWORK_TESTING is defined
(/opt/perl-5.38.0/bin/perl Makefile.PL exited with 0)

CPAN::Reporter: test results were not valid, No Makefile or Build file found.

No 'Makefile' created  NHORNE/Locale-Places-0.09.tar.gz
  /opt/perl-5.38.0/bin/perl Makefile.PL -- NOT OK
```
